import { AlertTriangle, ArrowUp, MessageCircleHeart } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { LoadingScreen } from '../components/ui/LoadingScreen'
import { api, type ChatMessage } from '../lib/api'

const welcome: ChatMessage = { id: 'welcome', role: 'assistant', created_at: new Date().toISOString(), content: 'Hello, I’m Nompilo. I’m here to share clear health information, help you prepare for clinic visits, and support you in deciding what to do next. What would you like to talk about today?' }

export function ChatPage() {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const bottomRef = useRef<HTMLDivElement>(null)
  useEffect(() => { void api.getMessages().then(setMessages).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => bottomRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages, sending])
  async function send(event: React.FormEvent) { event.preventDefault(); const value = draft.trim(); if (!value || sending) return; setDraft(''); setSending(true); setError(''); const optimistic: ChatMessage = { id: `pending-${Date.now()}`, role: 'user', content: value, created_at: new Date().toISOString() }; setMessages((current) => [...current, optimistic]); try { const response = await api.sendMessage(value); setMessages((current) => [...current.filter((item) => item.id !== optimistic.id), response.user_message, response.assistant_message]) } catch (reason) { setMessages((current) => current.filter((item) => item.id !== optimistic.id)); setDraft(value); setError(reason instanceof Error ? reason.message : 'Could not send your message.') } finally { setSending(false) } }
  if (loading) return <LoadingScreen />
  const shownMessages = messages.length ? messages : [welcome]
  return <div className="mx-auto flex max-w-3xl flex-col"><div><p className="text-sm font-semibold text-terracotta">AI health education</p><h1 className="page-heading mt-1">Talk to Nompilo</h1><p className="page-copy">A private space to ask questions, learn, and prepare for your next healthcare step.</p></div><Card className="mt-6 flex gap-3 border border-nude bg-[#FFF9F5] shadow-none"><AlertTriangle className="mt-0.5 shrink-0 text-terracotta" size={19} /><p className="text-sm leading-6 text-cocoa/75"><strong>Nompilo provides educational guidance, not medical diagnosis or emergency care.</strong> If you feel unsafe or have severe symptoms, contact a clinic, doctor, or emergency service now.</p></Card><section className="mt-5 min-h-[24rem] rounded-3xl bg-white p-4 shadow-card sm:p-6" aria-label="Nompilo conversation"><div className="space-y-4">{shownMessages.map((message) => <div className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`} key={message.id}><div className={`max-w-[88%] rounded-3xl px-4 py-3 text-sm leading-6 ${message.role === 'user' ? 'bg-terracotta text-white' : 'bg-sand text-cocoa'}`}><p>{message.content}</p>{message.role === 'assistant' && <p className="mt-2 border-t border-cocoa/10 pt-2 text-xs text-cocoa/55">Educational support only — a healthcare professional can give personal medical advice.</p>}</div></div>)}{sending && <div className="flex justify-start"><div className="flex items-center gap-2 rounded-3xl bg-sand px-4 py-3 text-sm text-cocoa/70"><span className="h-4 w-4 animate-spin rounded-full border-2 border-terracotta border-t-transparent" />Nompilo is preparing a response</div></div>}<div ref={bottomRef} /></div><form onSubmit={send} className="mt-6 border-t border-sand pt-4"><label className="sr-only" htmlFor="chat-message">Your message</label><div className="flex items-end gap-2"><textarea id="chat-message" value={draft} onChange={(event) => setDraft(event.target.value)} maxLength={3000} rows={2} placeholder="Type your health question…" className="focus-ring min-h-12 flex-1 resize-none rounded-2xl border border-sand px-4 py-3 text-sm placeholder:text-cocoa/40" /><Button type="submit" className="h-12 w-12 shrink-0 px-0" disabled={!draft.trim()} loading={sending} aria-label="Send message"><ArrowUp size={19} /></Button></div>{error && <p className="mt-2 text-sm font-medium text-rose" role="alert">{error}</p>}</form></section><div className="mt-4 flex items-center gap-2 text-xs leading-5 text-cocoa/55"><MessageCircleHeart size={15} className="text-terracotta" />Your conversation is saved securely to your account when the service is configured.</div></div>
}
