import { ArrowRight, BookOpen, CalendarDays, ChevronRight, HeartPulse, MessageCircleHeart, Stethoscope } from 'lucide-react'
import { Link, useOutletContext } from 'react-router-dom'
import { Card } from '../components/ui/Card'

const actions = [
  { to: '/chat', title: 'Talk to Nompilo', description: 'Ask a health question', icon: MessageCircleHeart, tone: 'bg-[#F6E5DD] text-terracotta' },
  { to: '/symptoms', title: 'Check symptoms', description: 'Understand what to do next', icon: Stethoscope, tone: 'bg-[#F0E8D5] text-[#927335]' },
  { to: '/period', title: 'Track your cycle', description: 'Log a period or view dates', icon: HeartPulse, tone: 'bg-[#F3E1E1] text-rose' },
  { to: '/appointments', title: 'Plan a visit', description: 'Prepare for an appointment', icon: CalendarDays, tone: 'bg-[#E5EEE8] text-sage' },
]

export function DashboardPage() {
  const { firstName } = useOutletContext<{ firstName: string }>()
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-semibold text-terracotta">Your health companion</p><h1 className="page-heading mt-1">Good to see you, {firstName}.</h1><p className="page-copy">How can we support your health today?</p><section className="mt-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Quick actions</h2><span className="text-xs font-medium text-cocoa/50">Choose where to begin</span></div><div className="grid gap-3 sm:grid-cols-2">{actions.map(({ to, title, description, icon: Icon, tone }) => <Link className="focus-ring group rounded-3xl" to={to} key={to}><Card className="flex min-h-29 items-center gap-4 transition duration-200 group-hover:-translate-y-0.5 group-hover:shadow-lift"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${tone}`}><Icon size={23} /></span><span className="min-w-0 flex-1"><span className="block font-bold">{title}</span><span className="mt-1 block text-sm text-cocoa/60">{description}</span></span><ChevronRight className="text-cocoa/35" size={20} /></Card></Link>)}</div></section><section className="mt-8 grid gap-4 lg:grid-cols-5"><Card className="lg:col-span-3"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex rounded-full bg-sand px-3 py-1 text-xs font-bold text-terracotta">Nompilo</span><h2 className="mt-4 font-display text-2xl font-bold">A listening ear for your health questions.</h2><p className="mt-2 max-w-md text-sm leading-6 text-cocoa/65">Get clear, supportive health information and prepare for your next step. Nompilo does not diagnose or replace a healthcare professional.</p></div><MessageCircleHeart className="shrink-0 text-terracotta" size={30} /></div><Link to="/chat" className="focus-ring mt-5 inline-flex items-center gap-2 rounded-xl text-sm font-bold text-terracotta hover:underline">Start a conversation <ArrowRight size={17} /></Link></Card><Card className="lg:col-span-2"><div className="flex h-full flex-col"><BookOpen className="text-terracotta" size={25} /><h2 className="mt-4 text-lg font-bold">Health library</h2><p className="mt-2 text-sm leading-6 text-cocoa/65">Trusted, easy-to-read topics for everyday health.</p><Link to="/library" className="focus-ring mt-auto pt-4 text-sm font-bold text-terracotta hover:underline">Explore topics</Link></div></Card></section><section className="mt-8 grid gap-4 md:grid-cols-2"><Card><div className="flex items-center justify-between"><div><h2 className="font-bold">Upcoming appointments</h2><p className="mt-1 text-sm text-cocoa/60">Your visits will appear here.</p></div><CalendarDays className="text-sage" size={24} /></div></Card><Card><div className="flex items-center justify-between"><div><h2 className="font-bold">Period tracker</h2><p className="mt-1 text-sm text-cocoa/60">Your cycle information will appear here.</p></div><HeartPulse className="text-rose" size={24} /></div></Card></section></div>
}
