import { BookOpen, ChevronRight, HeartHandshake, Leaf, ShieldPlus } from 'lucide-react'
import { useState } from 'react'
import { Card } from '../components/ui/Card'
import { Modal } from '../components/ui/Modal'

type Article = { category: string; title: string; summary: string; content: string; icon: typeof BookOpen }
const articles: Article[] = [
  { category: 'Menstrual health', title: 'Understanding your menstrual cycle', summary: 'A gentle overview of periods, cycle changes, and when to ask for care.', content: 'Periods can vary in length and flow from person to person and from month to month. Tracking your cycle can help you notice patterns. Speak to a nurse or doctor if bleeding is unusually heavy, pain stops you from daily life, or your cycle changes suddenly.', icon: HeartHandshake },
  { category: 'Contraception', title: 'Choosing contraception', summary: 'Learn about the questions to take to a nurse or clinic.', content: 'Different contraception options suit different people and health needs. A trained healthcare professional can explain effectiveness, possible side effects, protection from pregnancy, and protection from STIs. You deserve time and clear answers when making a choice.', icon: ShieldPlus },
  { category: 'Pregnancy', title: 'Early pregnancy support', summary: 'Know the value of early, respectful antenatal care.', content: 'If you think you may be pregnant, a clinic can confirm pregnancy and discuss your options, health history, nutrition, and early antenatal care. Seek urgent care for severe pain, fainting, shoulder pain, or heavy bleeding.', icon: HeartHandshake },
  { category: 'STI awareness', title: 'STIs and testing', summary: 'Testing and treatment are private, normal parts of sexual health.', content: 'Many STIs do not cause noticeable symptoms, so testing can be important after new or unprotected sexual contact. Clinics can offer confidential advice, testing, treatment, and information about condoms. Avoid self-diagnosing from symptoms alone.', icon: ShieldPlus },
  { category: 'Mental wellness', title: 'Taking care of your mental wellbeing', summary: 'Small supportive steps and signs that you may need more help.', content: 'Stress, sadness, anxiety, and exhaustion can affect anyone. Rest, connection, routine, and talking to someone you trust may help. If you feel hopeless, unsafe, or think about harming yourself, contact emergency services, a crisis line, or a trusted healthcare professional immediately.', icon: HeartHandshake },
  { category: 'Nutrition', title: 'Everyday nourishing habits', summary: 'Practical nutrition foundations that fit real life.', content: 'Regular meals with a variety of foods can support energy and wellbeing. When possible, include vegetables or fruit, protein, whole grains, and water. If you have a health condition, are pregnant, or have concerns about eating, a nurse or dietitian can give personal guidance.', icon: Leaf },
  { category: "Women's health", title: 'Preventive care matters', summary: 'A reminder to listen to your body and attend recommended screenings.', content: 'Preventive visits can help you discuss contraception, sexual health, blood pressure, mental wellbeing, and changes in your body. Ask a local clinic which screening services are right for you based on your age and health history.', icon: BookOpen },
]

export function HealthLibraryPage() {
  const [category, setCategory] = useState('All'); const [selected, setSelected] = useState<Article | null>(null); const categories = ['All', ...new Set(articles.map((article) => article.category))]; const visible = category === 'All' ? articles : articles.filter((article) => article.category === category)
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-semibold text-terracotta">Trusted health education</p><h1 className="page-heading mt-1">Health library</h1><p className="page-copy">Clear, respectful information to support your conversations with healthcare professionals.</p><div className="mt-6 flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`focus-ring shrink-0 rounded-full px-4 py-2 text-sm font-semibold transition ${category === item ? 'bg-terracotta text-white' : 'bg-white text-cocoa/70 shadow-card hover:bg-sand'}`}>{item}</button>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((article) => { const Icon = article.icon; return <button key={article.title} onClick={() => setSelected(article)} className="focus-ring text-left"><Card className="group h-full transition group-hover:-translate-y-0.5 group-hover:shadow-lift"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sand text-terracotta"><Icon size={21} /></span><p className="mt-5 text-xs font-bold uppercase tracking-wide text-terracotta">{article.category}</p><h2 className="mt-2 text-lg font-bold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-cocoa/65">{article.summary}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-terracotta">Read more <ChevronRight size={17} /></span></Card></button> })}</div><Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.title ?? 'Health library'}>{selected && <div><p className="text-xs font-bold uppercase tracking-wide text-terracotta">{selected.category}</p><p className="mt-4 text-sm leading-7 text-cocoa/75">{selected.content}</p><p className="mt-6 rounded-2xl bg-cream p-3 text-xs leading-5 text-cocoa/60">This library is for education and will support English, isiZulu, Sesotho, and isiXhosa content as the library expands.</p></div>}</Modal></div>
}
